name: data_lab
channels:
  - defaults
  - conda-forge
  - conda-main
  - conda-r
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=2.0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - click=7.1.1
  - cloudpickle=1.3.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.9.0
  - dask-core=2.9.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.14.0
  - entrypoints=0.3
  - freetype=2.9.1
  - fsspec=0.7.1
  - heapdict=1.0.1
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - kiwisolver=1.0.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - llvmlite=0.31.0
  - locket=0.2.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - msgpack-python=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.2
  - notebook=6.0.3
  - numba=0.47.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1f
  - packaging=20.3
  - pandas=0.25.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - partd=1.1.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - pygments=2.6.1
  - pyparsing=2.4.6
  - pyrsistent=0.16.0
  - python=3.8.2
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.3.1
  - pyzmq=18.1.1
  - readline=8.0
  - scipy=1.4.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sortedcontainers=2.1.0
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - tbb=2020.0
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.1
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=2.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - chardet==3.0.4
    - idna==2.10
    - json5==0.9.5
    - jupyterlab==2.2.1
    - jupyterlab-server==1.2.0
    - requests==2.24.0
    - urllib3==1.25.10

