name: data_lab
channels:
  - defaults
dependencies:
  - dask=2.9.0
  - ipykernel=5.1.4
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - numba=0.47.0
  - numpy=1.18.1
  - pandas=0.25.3
  - pip=20.0.2
  - psutil=5.6.7
  - seaborn=0.9.0
